export const AUDIT_LOGS_REPOSITORY = Symbol("AUDIT_LOGS_REPOSITORY");
export const DEPOSIT_WALLETS_REPOSITORY = Symbol("DEPOSIT_WALLETS_REPOSITORY");
export const FUNDING_REPOSITORY = Symbol("FUNDING_REPOSITORY");
export const ORDERS_REPOSITORY = Symbol("ORDERS_REPOSITORY");
export const SYNC_JOB_RUNS_REPOSITORY = Symbol("SYNC_JOB_RUNS_REPOSITORY");
export const WALLETS_REPOSITORY = Symbol("WALLETS_REPOSITORY");
